### ISSUE TITLE
wrong file /Configuration/TCA/Overrides/sys_template.php

### ISSUE THREAD

**Issue by franzholz** [romm/formz_example#8]
The extension uses the file  /Configuration/TCA/Overrides/sys_template.php.
However no modification on the TCA of the table sys_template is done. Instead the TCA of tt_content is modified. This is wrong. The name of the file must be tt_content.php because of this.

    $GLOBALS['TCA']['tt_content']['types']['list']['subtypes_excludelist'][$defaultPluginKey] = 'recursive,select_key,pages';

**Comment by franzholz** [comment]
And additionally the " must be used instead of ' (coding guidelines):

    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPiFlexFormValue($defaultPluginKey, "FILE:EXT:$extensionKey/Configuration/FlexForms/FlexForm.xml");

**Comment by romm** [comment]
Thanks for noticing!
